# Generated by Django 3.1.7 on 2021-04-05 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('address', models.TextField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('country', models.CharField(choices=[('Australia', 'Australia'), ('Bangladesh', 'Bangladesh'), ('Brazil', 'Brazil'), ('Canada', 'Canada'), ('China', 'China'), ('England', 'England'), ('France', 'France'), ('Germany', 'Germany'), ('India', 'India'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('Mexico', 'Mexico'), ('Nepal', 'Nepal'), ('Russia', 'Russia'), ('Singapore', 'Singapore')], max_length=50)),
                ('markspercentage', models.FloatField(blank=True, null=True)),
                ('User', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
