# Generated by Django 3.1.7 on 2021-04-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=19, null=True)),
                ('mobile', models.CharField(max_length=16, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('addres', models.TextField(null=True)),
                ('gender', models.BooleanField()),
                ('countries', models.CharField(max_length=20, null=True)),
                ('brances', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentDetails',
        ),
    ]
