# Generated by Django 3.1.7 on 2021-04-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210406_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_data',
            old_name='addres',
            new_name='address',
        ),
    ]
