# Generated by Django 3.1.7 on 2021-04-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210406_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_data',
            old_name='brances',
            new_name='branches',
        ),
    ]
