# Generated by Django 3.1.7 on 2021-04-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210407_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='student_data',
            name='branches',
        ),
    ]
