# Generated by Django 3.1.7 on 2021-04-08 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210408_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='Group_Data',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.group_data'),
        ),
    ]
